-- ========================================================
-- On-Page SEO SQL Migration for odooservice.de (Rank Math)
-- Language: Deutsch (de_DE)
-- ========================================================

-- SEO PostMeta for Home Page (ID: 10, Slug: home-page)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_title', 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_description', 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_focus_keyword', 'Odoo Agentur,Odoo Implementierung,Odoo Beratung Deutschland,Odoo ERP Partner,Odoo Migration,ERP System Einführung KMU') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Agentur,Odoo Implementierung,Odoo Beratung Deutschland,Odoo ERP Partner,Odoo Migration,ERP System Einführung KMU';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_canonical_url', 'https://odooservice.de/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_facebook_title', 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_facebook_description', 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_twitter_title', 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Agentur Deutschland | Implementierung, Beratung & Migration';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_twitter_description', 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Ihre führende Odoo Agentur für Implementierung, Beratung & Migration. Maßgeschneiderte Odoo ERP-Lösungen für maximale Effizienz. Jetzt Erstgespräch anfragen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (10, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for Services Page (ID: 17, Slug: odoo-dienstleistungen)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_title', 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_description', 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.') ON DUPLICATE KEY UPDATE `meta_value` = 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_focus_keyword', 'Odoo Dienstleistungen,Odoo Services,Odoo ERP Entwicklung,Odoo Modulanpassung,Odoo JTL Migration,Odoo Schnittstellen API,Odoo Support Wartung') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Dienstleistungen,Odoo Services,Odoo ERP Entwicklung,Odoo Modulanpassung,Odoo JTL Migration,Odoo Schnittstellen API,Odoo Support Wartung';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_canonical_url', 'https://odooservice.de/odoo-dienstleistungen/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/odoo-dienstleistungen/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_facebook_title', 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_facebook_description', 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.') ON DUPLICATE KEY UPDATE `meta_value` = 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_twitter_title', 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Dienstleistungen & Services: Beratung, Entwicklung & Support';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_twitter_description', 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.') ON DUPLICATE KEY UPDATE `meta_value` = 'Entdecken Sie unsere Odoo Dienstleistungen: ERP-Implementierung, JTL-Migration, Modulentwicklung, API-Schnittstellen & Support. Individuell für Ihr Business.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (17, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for About Us Page (ID: 21, Slug: about-us)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_title', 'Odoo Partner & Experten | Über Odoo Service & unser Team') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Partner & Experten | Über Odoo Service & unser Team';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_description', 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.') ON DUPLICATE KEY UPDATE `meta_value` = 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_focus_keyword', 'Odoo Partner Deutschland,Odoo Experten Team,Odoo Spezialisten,Odoo Beratung DACH,Odoo Agentur Erfahrung') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Partner Deutschland,Odoo Experten Team,Odoo Spezialisten,Odoo Beratung DACH,Odoo Agentur Erfahrung';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_canonical_url', 'https://odooservice.de/about-us/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/about-us/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_facebook_title', 'Odoo Partner & Experten | Über Odoo Service & unser Team') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Partner & Experten | Über Odoo Service & unser Team';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_facebook_description', 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.') ON DUPLICATE KEY UPDATE `meta_value` = 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_twitter_title', 'Odoo Partner & Experten | Über Odoo Service & unser Team') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Partner & Experten | Über Odoo Service & unser Team';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_twitter_description', 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.') ON DUPLICATE KEY UPDATE `meta_value` = 'Lernen Sie Odoo Service kennen: Ihr erfahrener Odoo Partner für ganzheitliche ERP-Lösungen im DACH-Raum. Persönliche Beratung, technisches Know-how & Erfolg.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (21, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for Contact Page (ID: 25, Slug: contact)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_title', 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_description', 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.') ON DUPLICATE KEY UPDATE `meta_value` = 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_focus_keyword', 'Odoo Beratung Kontakt,Odoo Erstgespräch anfragen,Odoo Agentur Kontakt,Odoo Experte anfragen,Odoo Projektberatung') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Beratung Kontakt,Odoo Erstgespräch anfragen,Odoo Agentur Kontakt,Odoo Experte anfragen,Odoo Projektberatung';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_canonical_url', 'https://odooservice.de/contact/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/contact/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_facebook_title', 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_facebook_description', 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.') ON DUPLICATE KEY UPDATE `meta_value` = 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_twitter_title', 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Beratung & Kontakt | Kostenloses Erstgespräch anfragen';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_twitter_description', 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.') ON DUPLICATE KEY UPDATE `meta_value` = 'Starten Sie Ihr Odoo Projekt mit Odoo Service. Vereinbaren Sie jetzt ein unverbindliches Erstgespräch für Implementierung, Migration oder Support.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (25, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for References Page (ID: 688, Slug: references-page)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_title', 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_description', 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_focus_keyword', 'Odoo Referenzen,Odoo Projekte,Odoo Erfolgsgeschichten,Odoo Case Studies,JTL zu Odoo Migration Referenz,Odoo Einführung Großhandel') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Referenzen,Odoo Projekte,Odoo Erfolgsgeschichten,Odoo Case Studies,JTL zu Odoo Migration Referenz,Odoo Einführung Großhandel';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_canonical_url', 'https://odooservice.de/references-page/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/references-page/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_facebook_title', 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_facebook_description', 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_twitter_title', 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Referenzen & Case Studies | Erfolgreiche Kundenprojekte';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_twitter_description', 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!') ON DUPLICATE KEY UPDATE `meta_value` = 'Erfolgreiche Odoo Projekte & Kundenreferenzen: Von der JTL-Migration bis zur ERP-Komplettlösung für Großhandel, Retail und Fertigung. Jetzt Case Studies lesen!';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (688, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for Impressum (ID: 836, Slug: impressum)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_title', 'Impressum | Odoo Service Rechtliche Angaben') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum | Odoo Service Rechtliche Angaben';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_description', 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_focus_keyword', 'Odoo Service Impressum') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Service Impressum';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_canonical_url', 'https://odooservice.de/impressum/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/impressum/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_facebook_title', 'Impressum | Odoo Service Rechtliche Angaben') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum | Odoo Service Rechtliche Angaben';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_facebook_description', 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_twitter_title', 'Impressum | Odoo Service Rechtliche Angaben') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum | Odoo Service Rechtliche Angaben';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_twitter_description', 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.') ON DUPLICATE KEY UPDATE `meta_value` = 'Impressum von Odoo Service: Rechtliche Angaben, Unternehmensinformationen, Registernummern und Kontaktdaten.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (836, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for AGB (ID: 881, Slug: geschaftsbedingun)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_title', 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_description', 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_focus_keyword', 'Odoo Service AGB') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Service AGB';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_canonical_url', 'https://odooservice.de/geschaftsbedingun/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/geschaftsbedingun/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_facebook_title', 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_facebook_description', 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_twitter_title', 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen (AGB) | Odoo Service';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_twitter_description', 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.') ON DUPLICATE KEY UPDATE `meta_value` = 'Allgemeine Geschäftsbedingungen von Odoo Service: Informationen zu Leistungen, Vergütung, Verträgen und Datenschutz.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (881, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for Datenschutz (ID: 3, Slug: privacy-policy)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_title', 'Datenschutzerklärung | Odoo Service DSGVO-Konform') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung | Odoo Service DSGVO-Konform';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_description', 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_focus_keyword', 'Odoo Service Datenschutz') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Service Datenschutz';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_canonical_url', 'https://odooservice.de/privacy-policy/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/privacy-policy/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_facebook_title', 'Datenschutzerklärung | Odoo Service DSGVO-Konform') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung | Odoo Service DSGVO-Konform';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_facebook_description', 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_twitter_title', 'Datenschutzerklärung | Odoo Service DSGVO-Konform') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung | Odoo Service DSGVO-Konform';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_twitter_description', 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.') ON DUPLICATE KEY UPDATE `meta_value` = 'Datenschutzerklärung von Odoo Service: Erfahren Sie alles über den Schutz und die Verarbeitung Ihrer personenbezogenen Daten gemäß DSGVO.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (3, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';

-- SEO PostMeta for Cookie-Richtlinie (ID: 1723, Slug: cookie-policy)
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_title', 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies') ON DUPLICATE KEY UPDATE `meta_value` = 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_description', 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.') ON DUPLICATE KEY UPDATE `meta_value` = 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_focus_keyword', 'Odoo Service Cookie Richtlinie') ON DUPLICATE KEY UPDATE `meta_value` = 'Odoo Service Cookie Richtlinie';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_canonical_url', 'https://odooservice.de/cookie-policy/') ON DUPLICATE KEY UPDATE `meta_value` = 'https://odooservice.de/cookie-policy/';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_robots', 'a:1:{i:0;s:5:"index";}') ON DUPLICATE KEY UPDATE `meta_value` = 'a:1:{i:0;s:5:"index";}';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_facebook_title', 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies') ON DUPLICATE KEY UPDATE `meta_value` = 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_facebook_description', 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.') ON DUPLICATE KEY UPDATE `meta_value` = 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_twitter_title', 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies') ON DUPLICATE KEY UPDATE `meta_value` = 'Cookie-Richtlinie | Odoo Service Hinweise zu Cookies';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_twitter_description', 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.') ON DUPLICATE KEY UPDATE `meta_value` = 'Informationen über die Verwendung von Cookies und ähnlichen Technologien auf der Website von Odoo Service.';
INSERT INTO `wp_postmeta` (`post_id`, `meta_key`, `meta_value`) VALUES (1723, 'rank_math_twitter_use_facebook', 'off') ON DUPLICATE KEY UPDATE `meta_value` = 'off';
